display_errors=Off
log_errors=On
error_reporting=E_ALL
expose_php=Off

memory_limit=256M
max_execution_time=60
max_input_time=60
post_max_size=20M
upload_max_filesize=20M

session.use_strict_mode=1
session.use_only_cookies=1
session.cookie_httponly=1
session.cookie_samesite=Lax
session.sid_length=48
session.sid_bits_per_character=6

date.timezone=America/Bogota
